name: ShellCheck

on:
  push:
    paths:
      - "**.sh"
  pull_request:
    paths:
      - "**.sh"

jobs:
  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@2.0.0
